name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull-requests:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "Goodbye Wodld..."
        shell: bash
